#+TITLE: Docx4j

* 개요
- java 코드로 ms 워드 문서를 작성할 수 있게 해주는 프레임웍


* 특징
- OpenXML 스펙을 자바 코드로 구현한 프로젝트이다. 
  (C#, VB 도 있고, 아마도 파이썬이나 다른 언어로도 구현된 것이 있을 것이다.)
- WML (WordProcessingML) 은 OpenXML 스펙의 일부이다. MS워드는 WML을 사용한다.


* Open XML
** 개요
- MS 오피스 제품군의 문서의 컨텐츠를 정의하는 언어이다.
- 워드를 위한 WordprocessingML, 엑셀을 위한 SpreadsheetML, 파워포인트를 위한 PresentationML 이 있다.
- ISO/IEC 29500 에 정의됨. 

** WordprocessingML
*** 기본 정보
- docx 파일은 사실 zip 포맷이다!
- zip 파일안에 각 기능별 폴더와 XML파일들이 있는 구조이다.

*** 폴더 구조
**** _rels
- Relationships 파일이 저장되어 있다. 
- Relationship 파일 자체는 링크정보만 제공할 뿐이다.

*** 엘레먼트
**** <w:document></w:document>
- 최상위.  문서의 컨텐츠를 정의한다.

*** Document Body
document body 에는 두 가지 main group 이 있다. 

**** block-level content
- 메인 스트럭처를 제공한다.
- paragraph, tables 같은 것
- inline content 를 포함한다.
		
**** inline content
- text 와 image 등
- text 는 여러개의 다른 run 들로 나뉘어 진다. 
- run 은 포맷팅을 적용할 수 있는 가장 작은 단위이다.



*** lsdException
-LatentStyleException

** SpreadsheetML

** PresentationML

** DrawingML



* 클래스 계층 구조
- 다음 XML 계층구조로 docx파일이 구성된다.
- 스타일은 부모 엘레먼트에 적용된 것이 있으면 상속받는 형태이다. HTML의 스타일 적용과 비슷하다.
- 자식 엘레먼트에서 새로 적용한 스타일이 있으면 그 것이 우선된다.

** WordprocessingMLPackage
*** MainDocumentPart
**** Document
***** Body
****** P
- Paragraph
- 레이아웃을 위한 기본 유닛이다.
- 마진, 탭 등을 적용가능하다.

******* R
- Run
- 특정 텍스트 영역(region)을  정의(define)한다.
- 주로 문장을 표현할 때 사용한다.

******** Text
- 실제 텍스트
******** FldChar
- FieldChar
******** Rpr
- Run properties

#+BEGIN_SRC xml
<w:rPr>
      <w:rFonts w:ascii="Meiryo" w:hAnsi="Meiryo" w:eastAsia="Meiryo" w:cs="Meiryo"/>
       <w:sz w:val="20"/>
       <w:szCs w:val="20"/>
       <w:lang w:val="ja-JP" w:eastAsia="ja-JP" w:bidi="en-US"/>
</w:rPr>
#+END_SRC

********* RFonts
- 폰트를 지정한다. 지정할 수 있는 속성값은 다음과 같다.
- ASCII : ASCII 범위의 캐릭터에 대해서 지정할 폰트
- hAnsi :High ANSI
- cs (Complex Script) : 아스키 범위를 넘어서는 유니코드 캐릭터에 대한 폰트
- EastAsia

********* sz
- 사이즈
- 지정된 값의 1/2 이 폰트의 사이즈가 된다. (20일 경우 폰트 사이즈10)

********* szCs
- FontSizeComplexScript
- complex script 캐릭터인 경우 적용되는 폰트 사이즈

******* PPr
- ParagraphProperties 
- 문단(패러그래프)의 스타일 정의
#+BEGIN_SRC xml
<w:pPr>
   <w:spacing w:before="360" w:after="120" w:line="480" w:lineRule="auto" w:beforeAutospacing="0" w:afterAutospacing="0"/>
</w:pPr>
#+END_SRC



******** spacing
- after : 문단의 마지막 라인이 끝난 뒤에 추가될 공간을 정의
- before : 문단의 첫 번째 라인이 시작하기 전에 추가될 공간을 정의
- line : 문장 사이의 수직 spacing 공간을 정의. (vertical spacing)

#+CAPTION: PPr 의 vertical spacing을 지정하는 java 예제
#+BEGIN_SRC Java
    PPr rightPPr = factory.createPPr(); 
	rightPPr.setJc(jc);
	Spacing spacing = new Spacing();
	spacing.setAfter(new BigInteger("100"));
	rightPPr.setSpacing(spacing);
#+END_SRC

******** PStyle
- ParagraphStyle

******* NumPr
- Number Properties
******** NumId
숫자 값

******** Ilvl
- 숫자 레벨 (뎁스)
- 탑 레벨은 0 임. 

******* Jc
- Justification
- 정렬 속성을 정의
- 텍스트의 중앙정렬, 왼쪽 정렬, 오른쪽 정렬 등을 지정할 수 있다. 

******* ind
- indentation
- 들여쓰기 속성의 적의

*** NumberingDefinitionsPart
**** Emulator


* 트러블 슈팅
** conversion (목차 만드는 서비스) 서버 Connection Error
*** 현상
워드 문서 생성을 시도하면 다음과 같은 에러가 발생한다.

#+BEGIN_SRC Java
Looks like your endpoint URL 'http://[My IP]:9016/v1/00000000-0000-0000-0000-000000000000/convert' is wrong

org.docx4j.toc.TocException: Error in toc web service at http://[My IP]:9016/v1/00000000-0000-0000-0000-000000000000/convert
Connect to [My IP]:9016 [/[My IP]] failed: Connection refused: connect
	at org.docx4j.toc.TocGenerator.getPageNumbersMapViaService(TocGenerator.java:717)
	at org.docx4j.toc.TocGenerator.getPageNumbersMap(TocGenerator.java:663)
	at org.docx4j.toc.TocGenerator.populateToc(TocGenerator.java:438)
	at org.docx4j.toc.TocGenerator.generateToc(TocGenerator.java:342)
	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:561)
	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:509)
	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:489)
	....
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.docx4j.services.client.ConversionException: Connect to [My IP]:9016 [/[My IP]] failed: Connection refused: connect
	at org.docx4j.services.client.ConverterHttp.execute(ConverterHttp.java:243)
	at org.docx4j.services.client.ConverterHttp.convert(ConverterHttp.java:190)
	at org.docx4j.toc.TocGenerator.getPageNumbersMapViaService(TocGenerator.java:701)
	... 92 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to [My IP]:9016 [/[My IP]] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.docx4j.services.client.ConverterHttp.execute(ConverterHttp.java:212)
	... 94 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)

	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
#+END_SRC

*** 원인 분석
현재 상황은 다음과 같다. 
- netstat 으로 확인해보면 9016 포트는 Listening 상태이다. 
- http://localhost:9016 으로 접속하면 404 not found 메세지가 출력된다. 이 것으로 서버가 살아있다는 것을 알 수 있다. 
- http://[MyIP]:9016 으로 접속하면 connection refused 가 출력된다. 아마도 이 것이 원인인 것 같다. 
- 왜 저런 반응이 나타나는 걸까? localhost 일 때랑 실제 IP를 입력했을 때 반응이 다른 이유는?
- *로컬의 컨버터 서비스가 localhost 혹은 127.0.0.1 일 때만 서비스하도록 설정되어 있었다.*

*** 해결
**** 서비스 IP 변경
- 레지스트리 수정으로 들어간다. 
- HKEY_LOCAL_MACHINE\SOFTWARE\PLUTEXT_SERVICE_ARGS 로 찾아 들어간다. 
- SERVICE_ARGS 값이 localhost:9016 으로 되어 있다. 
- 이 것을 [로컬IP]:9016 으로 바꿔준다.
- 제어판 > 설정 > 로컬 서비스에서 'PlutextDocumentServices'를 찾아 서비스를 재시작한다.


**** 로컬 PC의 방화벽 설정 변경
- 외부로부터의 접속을 로컬 방화벽에서 막고 있는 경우가 있다. 
- 방화벽 설정에서 허용할 서비스에 pdsd.exe를 추가해준다.

* 기타 정보
** 컨버팅 서비스를 로컬 PC에 설치한 경우(Windows)
- 컨버팅 서버 exe 파일 위치 : C:\Program Files (x86)\PlutextDocumentServices\pdsd.exe
- 로그파일 위치 : C:\ProgramData\PLUTEXT\logs\pdsd.log
- 설정 값 : HKEY_LOCAL_MACHINE\SOFTWARE\PLUTEXT_SERVICE_ARGS
- 설정 값에서 서비스 IP/포트나 로그 파일 경로, VERBOSE 설정등을 바꿀 수 있다.
- 서버 재시작을 하고 싶은 경우 : 제어판 > 설정 > 로컬 서비스에서 'PlutextDocumentServices' 라는 것이 등록되어 있다. 이 것을 중지하고 재시작하면 된다.


* 참고자료
- wml 설명 : https://www.tutorialspoint.com/wml/wml_elements.htm
- 소스코드 : https://github.com/plutext/docx4j/blob/master/src/main/java/org/docx4j/
- 샘클코드 : https://github.com/plutext/docx4j/tree/master/src/samples/docx4j/org/docx4j/samples
- 폰트변경 : http://www.docx4java.org/forums/docx-java-f6/setting-font-in-default-styles-t388.html
- OpenXML 설명 : http://officeopenxml.com/WPspacing.php
- OpenXML 매뉴얼 : openxmldeveloper.org/cfs.../Open-XML-Explained.pdf



