* You weren't meant to have a boss
URL : http://www.jimmyrim.com/168, http://paulgraham.com/boss.html

Technology tends to separate normal from natural. 
기술은 일상의 것들을 자연스럽지 못하게 하는 경향이 있다. 
Our bodies weren't designed to eat the foods that people in rich countries eat, or to get so little exercise.
우리의 육체는 부유한 국가들에서 흔히 먹는 음식들을 먹으며 살도록, 혹은 거의 운동을 하지 않도록 설계되지 않았다. 
There may be a similar problem with the way we work: a normal job may be as bad for us intellectually as white flour or sugar is for us physically. 
우리가 일하는 방식에서도 이런 비슷한 문제를 찾을 수 있는데, 흰밀가루나 설탕이 육체적으로 유해하듯이 보통 사람들이 갖는 직업이 정신적으로 유해할 수 있다는 것이다. 

I began to suspect this after spending several years working with startup founders. 
나는 스타트업의 창업자들과 수년 동안 일하면서 이러한 문제점에 대해 생각하기 시작했다. 
I've now worked with over 200 of them, and I've noticed a definite difference between programmers working on their own startups 
and those working for large organizations.
지금까지 나는 200명이 넘는 창업자들과 일해왔으며 직접 회사를 차리는 프로그래머들과 대기업에 들어가는 프로그래머들 사이의 명확한 차이점을 발견했다.
I wouldn't say founder seem happier, necessarily; starting a startup can be very stressful.
물론 창업자들이 꼭 행복해 보였다는 것은 아니다. 스타트업을 시작하는 일은 굉장히 스트레스를 받을 수 있는 일이기 때문이다.

