* 개요
이맥스에서 파이썬 개발환경 세팅

* 필요한 기능 목록
** IDE (Major Mode)
Python-mode

** 문법체크 (Flycheck)
flymake의 파이썬 판은 pyflakes

M-x pyflakes 를 실행하면 해당 파이썬 스크립트를 컴파일하면서 오류가 나는 부분을 알려준다. 



** 코드템플릿 (YASnippet)
주석 (doc string)

참고

주석도 다양한 스타일이 있는 듯하다. 크게 세 가지가 있는 듯한데, 

reStructuredText , Epydoc format, 그리고 google format 이다.


** 코드자동완성(jedi)

참고 : http://tkf.github.io/emacs-jedi/latest/




virtualenv 라는 툴이 설치되어 있어야 한다고 한다.

** virtualenv
*** 개요
파이썬 해킹에서 각 프로젝트별로 다른 의존성을 관리해주는 툴이다.

*** 설치
=sudo apt-get install python-pip python-dev build-essential=
=sudo pip install virtualenv virtualenvwrapper=
=sudo pip install --upgrade pip=

** 코드스타일 (인덴트, 괄호 자동완성 등)
#+BEGIN_SRC elisp 
		(add-hook 'python-mode-hook
          '(lambda ()
             (setq indent-tabs-mode nil)
             (setq index-level 4)
             (setq python-indent 4)
             (setq tab-width 4)))
#+END_SRC




** 소스코드 점프 / 함수 리스트 표시
*** 코드 점프
jedi 의 goto-definition (C-c .) 기능으로 가능
		
*** 되돌아 가기
goto-definition-pop-marker (C-c ,)

*** 함수리스트
i-menu-list
	
** 인터랙티브 환경
ipython

파이썬 내장 REPL을 더욱 발전시킨 것. 

An enhnaced Interactive Python

pip install ipython




** 디버깅
pdb를 사용한다.

*** 간단실행법

1. 디버깅하고 싶은 곳에 다음 라인을 추가한다. 
=import pdb; pdb.set_trace()=

2. 해당 프로그램을 실행하면 pdb가 로딩된다. (python [name].py)

*** 커맨드 목록
- l(ist) : Displays 11 lines around the current line or continue the previous listing. 
- s(tep) : Execute the current line, stop at the first possible occasion. 
- n(ext) : Continue execution until the next line in the current function is reached or it returns.
- b(reak) : Set a breakpoint (depending on the argument provided).
- r(eturn) : Continue execution until the current function returns. 
- h(elp) : Without argument, print the list of available commands. With a command as an argument, print help about that command. 
- cl(ear) : clear breakpoints

*** 함수
len() : 변수의 길이를 출력해준다.
dir() : 인스턴스 변수가 가진 메서드와 속성 값들을 출력해준다.

*** 참고 URL
https://github.com/spiside/pdb-tutorial


** 테스트 프레임웍

* 참고 URL
파이썬 개발환경 세팅
			
http://futurismo.biz/archives/2680
