#+TITLE: 진단 케이스 /대응방법 정리
#+AUTHOR: jwmoon

* 개요
다양한 공격 방법에 대한 개요 및 대응방법 등을 정리해둔 문서입니다. 


* XST (Cross Site Tracing)
** 개요
TRACE 메서드가 허용되어 있어 XST (Cross Site Tracing)공격이 성립할 가능성이 있습니다. 
TRACE 메서드가 허용된 서버는 HTTP 요청을 그대로 HTTP 응답에 포함해서 회신하게 됩니다. 
이 공격을 악용하면 XSS 방어수단 중 하나인 쿠키의 HttpOnly 속성을 우회할 수 있습니다. 

** 보안 임팩트
HTTP 응답에 포함되어 있는 쿠키정보나 베이직 인증 정보 등이 누출될 수 있습니다. 

** 대응방법
반드시 사용이 필요한 메서드 이외의 메서드는 사용을 제한하는 것이 좋습니다.
자세한 설정 방법은 별첨 가이드를 참고해주시기 바랍니다. 


* 세션고정 공격
** 개요
로그인 성공 후 서버에서 발급될 세션키의 값을 예측할 수 있어 세션 하이재킹의 한 종류인 세션 고정 공격(Session Fixation Attack)의 가능성이 있습니다.

** 보안임팩트
공격자가 임의의 사용자의 권한을 획득할 수 있습니다. 

** 공격 성립 조건
- 공격자는 피해자가 사용할 세션키의 값을 지정할 수 있어야 합니다. 
- 서버에 존재하는 다른 취약점 (XSS, 하이퍼링크 , 히든 필드, 메타 태그 삽입 등)을 이용합니다. 


** 공격 시나리오
1. 공격자는 피해자가 사이트에 접속시 사용할 세션키를 지정합니다.
2. 피해자는 지정된 세션키로 로그인을 시도합니다. 
3. 공격자가 동일한 세션키를 이용하여 서버에 접속하면 피해자의 권한으로 사이트를 이용할 수 있게 됩니다. 

** 대응방법
로그인을 성공하면 서버는 항상 새로운 세션을 발급하도록 합니다. 

** 참고 URL
https://www.owasp.org/index.php/Session_fixation


* X-Frame-Options 헤더 미설정
** 개요
- X-Frame-Options 응답 헤더는 어떤 페이지가 프레임(<frame>, <iframe>, <object> 등)내에서 렌더링될지 여부를 브라우저에게 지시하는데 사용됩니다.
- 클릭잭킹(clikcjacking) 공격을 피하기 위한 수단으로 이 헤더를 사용할 수 있습니다. 

다음과 같은 값을 설정할 수 있습니다. 

X-Frame-Options: DENY
X-Frame-Options: SAMEORIGIN
X-Frame-Options: ALLOW-FROM https://example.com/

각 설정 값의 의미는 다음과 같습니다. 
- DENY : 해당 페이지가 프레임안에서 렌더링되는 것을 금지
- SAMEORIGIN : 동일한 출처(도메인)의 페이지 내에서라면 해당 페이지가 프레임안에서 렌더링되는 것을 허용
- ALLOW-FROM : 지정된 URI 의 페이지 내에서라면 해당 페이지가 프레임안에서 렌더링되는 것을 허용

** 보안임팩트
- 이 헤더를 설정하지 않을 경우 사이트가 클릭 재킹 공격에 이용될 수 있습니다. 
- 의도치 않은 사용자 동작(아이템 삭제, 좋아요 버튼 클릭 등)이 발생할 수 있습니다. 

** 참고 URL
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options


* X-Content-Type-Options 헤더 미설정
** 개요
- 예전 브라우저는 사용자 경험을 높이기 위해 컨텐츠 타입을 sniffing (냄새를 맡아봄)해본 후 컨텐츠 타입을 유추해서 렌더링한 결과를 보여주었습니다. 
- 그러나 이 기능을 악용해 악의적인 사용자가 CSS Injection 등의 공격을 할 수 있게 되므로 컨텐츠 스니핑을 하지 못하도록 설정하는 것이 좋습니다. 

다음과 같은 헤더를 설정할 수 있습니다. 




* HSTS 헤더 미설정
** 개요


* X-XSS-Protection 헤더 미설정
** 개요


* Cache Control 헤더 미설정
** 개요



* 클릭 재킹
** 개요
웹 사용자가 자신이 클릭하고 있다고 인지하는 것과 다른 어떤 것을 클릭하게 속이는 기법

** 보안임팩트
공격자는 비밀정보를 유출시키거나 컴퓨터에 대한 제어를 획득할 수 있다. 

** 시나리오
- 플래시를 통해 사용자가 자신의 웹캠과 마이크를 활성화시키게 속인다.
- 사용자가 자신의 SNS 프로필 정보를 공개하게 속인다.
- 다른 사람의 트위터를 팔로우하게 속인다.
- 페이스북의 "좋아요"를 누르게 한다.
- 페이스북의 링크를 공유하게 한다.
- 구글 애드센스 프로그램에서 불법적인 수입을 올린다.



** 참고 URL
https://ko.wikipedia.org/wiki/%ED%81%B4%EB%A6%AD%EC%9E%AC%ED%82%B9
