#+TITLE: Session Fixation

* セッション固定攻撃
** 概要
ログインに成功した後、サーバーから発行されるセッションキーの値を予測することができ、セッションハイジャックの一種であるセッション固定攻撃（Session Fixation Attack）が成立する可能性があります。

** セキュリティインパクト
攻撃者が任意のユーザーの権限を取得することができます。

** 攻撃成立条件
攻撃者が、被害者が使用するセッションキーを指定できる必要があります。 （クライアント側のスクリプト（XSS）、ハイパーリンク、hiddenフィールド、メタタグなどが利用されます。）


** 攻撃シナリオ
1.攻撃者は、被害者がサイトにログインするときに使用するセッションキーを指定します。
2.被害者は指定されたセッションキーでログインを試みます。
3.攻撃者が、同じセッションキーを使用して、サーバーに接続することで、被害者の権限でサイトを利用することができます。

** 対応方法
ログインを成功すると、サーバーは、常に、新しいセッションを発行するようにします。

** 参考URL
https://www.owasp.org/index.php/Session_fixation


* 세션고정 공격
** 개요
로그인 성공 후 서버에서 발급될 세션키의 값을 예측할 수 있어 세션 하이재킹의 한 종류인 세션 고정 공격(Session Fixation Attack)의 가능성이 있습니다.

** 보안임팩트
공격자가 임의의 사용자의 권한을 획득할 수 있습니다. 

** 공격 성립 조건
- 공격자는 피해자가 사용할 세션키의 값을 지정할 수 있어야 합니다. 
- 서버에 존재하는 다른 취약점 (XSS, 하이퍼링크 , 히든 필드, 메타 태그 삽입 등)을 이용합니다. 


** 공격 시나리오
1. 공격자는 피해자가 사이트에 접속시 사용할 세션키를 지정합니다.
2. 피해자는 지정된 세션키로 로그인을 시도합니다. 
3. 공격자가 동일한 세션키를 이용하여 서버에 접속하면 피해자의 권한으로 사이트를 이용할 수 있게 됩니다. 

** 대응방법
로그인을 성공하면 서버는 항상 새로운 세션을 발급하도록 합니다. 

** 참고 URL
https://www.owasp.org/index.php/Session_fixation
