#+TITLE: X-Frame-Options Header 

* X-Frame-Optionsヘッダ未設定
** 概要
- X-Frame-Optionsレスポンスヘッダは、ページがフレーム（<frame>、<iframe>、<object>など）内でレンダリングされるかどうかをブラウザに指示するために使用されます。
- クリックジェクキン（clikcjacking）攻撃を防ぐ手段として、このヘッダを使用することができます。

次のような値を設定することができます。

X-Frame-Options：DENY
X-Frame-Options：SAMEORIGIN
X-Frame-Options：ALLOW-FROM https://example.com/

各設定値の意味は次のとおりです。
- DENY：このページは、フレームの中でレンダリングされることを禁止
- SAMEORIGIN：同じソース（ドメイン）のページ内であれば、そのページがフレーム内にレンダリングされることを許可
- ALLOW-FROM：指定されたURIのページ内であれば、そのページがフレーム内にレンダリングされることを許可

** 参考URL
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options


* X-Frame-Options 헤더 미설정
** 개요
- X-Frame-Options 응답 헤더는 어떤 페이지가 프레임(<frame>, <iframe>, <object> 등)내에서 렌더링될지 여부를 브라우저에게 지시하는데 사용됩니다.
- 클릭잭킹(clikcjacking) 공격을 피하기 위한 수단으로 이 헤더를 사용할 수 있습니다. 

다음과 같은 값을 설정할 수 있습니다. 

X-Frame-Options: DENY
X-Frame-Options: SAMEORIGIN
X-Frame-Options: ALLOW-FROM https://example.com/

각 설정 값의 의미는 다음과 같습니다. 
- DENY : 해당 페이지가 프레임안에서 렌더링되는 것을 금지
- SAMEORIGIN : 동일한 출처(도메인)의 페이지 내에서라면 해당 페이지가 프레임안에서 렌더링되는 것을 허용
- ALLOW-FROM : 지정된 URI 의 페이지 내에서라면 해당 페이지가 프레임안에서 렌더링되는 것을 허용

** 보안임팩트
- 이 헤더를 설정하지 않을 경우 사이트가 클릭 재킹 공격에 이용될 수 있습니다. 
- 의도치 않은 사용자 동작(아이템 삭제, 좋아요 버튼 클릭 등)이 발생할 수 있습니다. 

** 참고 URL
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
