* 경제적 불평등

폴 그레이엄의 경제적 불평등(Economic inequality)을 번역한 글입니다.

원문출처 : http://paulgraham.com/ineq.html

2016년 1월

1970년대 이래, 미국의 경제적 불평등은 극적으로 증가해왔다. 그리고 특히, 부자들은 더욱 부자가 되었다. 이 주제에 대해 글을 작성하는 거의 모든 사람들이 경제적 불평등은 감소되어야 한다고 말한다. 

나는 이 문제에 대해 관심이 있는데, 왜냐하면 내가 스타트업을 시작하는 것을 돕는 와이 컴비네이터라는 회사의 창업자 중 한 명이기 때문이다. 거의 정의대로, 만약 스타트업이 성공하면 창업자들은 부자가 된다. 그 말은 내가 스타트업 창업자들을 돕는 것으로 경제적 불평등이 증가하는 것을 도와왔다는 의미이다. 만약 경제적 불평등이 감소되어야 한다면, 나는 창업자들을 돕지 말아야 한다. 누구도 그러면 안 된다. 

그러나 그 말은 맞지 않는 것 같다. 그렇다면 귀류법에 의해서 우리가 방금 들었던 주장-경제적 불평등이 줄어야 한다는 말-은 거짓일까? 그 말 역시 맞지 않는 것 같다. 어떤 사람들은 실제로 가난에 갖혀 태어나고있고 , 다른 한쪽에서는 펀드 매니저들이 세금을 반으로 줄이기 위해 법의 허점을 악용하고 있다. 이런 것은 분명히 나쁘다.  

이 퍼즐에 대한 해결책은 경제적 불평등은 하나가 아니라는 점을 깨닫는 것이다. 그 것은 어떤 아주 나쁜 것(아이들이 자신들의 가능성에 도달할 어떤 기회도 갖지 못하는 것)과 , 그리고 어떤 좋은 것(래리 페이지나 세르게이 브린이 당신이 온라인에서 어떤 것을 찾기 위해 사용하는 회사를 시작하는 것 같은)으로 이루어져 있다. 

만약 당신이 경제적 불평등을 이해하고 싶으면- 그리고 더 중요하게는, 당신이 그 것의 나쁜 측면을 고치고 싶다면- 당신은 두 부분을 따로 떼어 놓아야 한다. 그리고 최근에 이 주제에 쓰여진 글들은 아직 반대로 하고있다. : 경제적 불평등에 대한 모든 측면을 꽉 쥐어짜고 있는 것이다. 그 것이 마치 하나의 현상인 것처럼 말이다. 

가끔씩은 이 것이 이데올로기적인 이유 때문이기도 하다. 가끔씩은 작성자가 단지 아주 높은 레벨의 데이터만을 가지고, 그 것으로만 결론을 도출하기 때문이기도 하다. 마치 주정뱅이가 자기의 잃어버린 열쇠를 실제로 잃어버린 곳이 아니라 불빛이 더 밝다는 이유로 가로등 밑에서 찾는 것처럼 말이다. 가끔씩은 작가가 불평등의 핵심적인 측면을 이해하지 못했기 때문이기도 하다. 부의 창조에서 기술의 역할에 대해서처럼 말이다. 많은 시간동안, 어쩌면 대부분의 시간동안, 경제적 불평등에 대해서 글을 쓰는 것은 이 세가지를 결합한 것이었다.


