* 아파치2에서 바뀐점?
- 다국어 지원
- 서버API가 합리적으로 바꼈다.
- 구성이 단순화되었다.
- IPv6 지원기능 추가
- 멀티스레드 대응
- APR(Apache Portable Runtime) 사용 등
- 하지만 일반 유저가 느끼는 차이점은 거의 없는 편


* 아파치에서 프로세스가 여러개 생기는 이유?
- 미리 워커 프로세스를 만들어두고 요청이 올 때마다 할당하는 것. 
- 요청이 오면 만드는 게 아니라 미리 준비하고 있는다고 생각하면 될 듯

* www-user?
- 아파치2를 설치할 때 자동으로 추가되는 아파치 구동용 유저이다. 
- 보안을 위해서 아파치는 www-user 계정 권한으로 구동한다. 
- ROOT권한으로 구동될 경우 웹 서버 프로그램이 모든 시스템에 접근가능하기 때문

** 하지만 부모프로세스는 왜 root로 실행되는지?
https://webmasters.stackexchange.com/questions/27615/why-has-apache-begun-running-a-single-process-as-root-and-another-as-root-and-t 에서 찾았다.

이유는 1024보다 적은 번호의 포트로 대기하고 있어야 하기 때문이라고 한다(HTTP 80, HTTPS 443)
일반 유저는 그렇게 할 수 없다.

또한, 아파치 구동 시의 몇 가지 설정파일은 루트로만 읽을 수 있기 때문. 예를 들면, SSL 설정에서의 개인키 파일 등

* 어플리케이션 파일의 소유자는 누구로 되어 있어야 하는가?
Root? www-user?

https://serverfault.com/questions/357108/what-permissions-should-my-website-files-folders-have-on-a-linux-webserver 에서 찾았다. 

어쟀든 그룹은 www-user로 되어 있어야 한다. (아파치가 해당 파일에 접근가능해야 서비스 할 수 있으므로), 이때 권한은 5이면된다. (읽기+ 실행), 소유자는 해당 파일을 수정하는 유저로 설정하면 된다. 
750 권한이 추천된다. (소유자는 모두 가능, 그룹(웹서버 프로세스)는 읽기, 실행가능, Anonymous는 모두 불가능)

ex) jwmoon:www-data



* 구동과 종료

** 왜 여러가지 구동방법이 있는가?
지금 알고 있는 것만 해도...

- service apache2 [start/stop/restart]

- /usr/sbin/apache2 -k [start/stop]

- apache2ctl [start/stop]

- /etc/rd.d/init.d/apache2  [start/stop/restart]

여기에 추가하여 우분투에는...
- sudo systemctl [start/stop/restart] apache2.service

이 명령어들간의 차이는 뭔가? 왜 이렇게 헷갈리게 여러가지가 있는가?

왜인지는 모르겠지만 아파치 구동이나 종료에 문제가 있을 때 apache2ctl 을 사용하면 될 때가 있다. 

가장 강력한 커맨드인듯...

예를들면 sudo service apache2 stop으로 안내려가던것도 sudo apache2ctl stop 하면 내려간다.


* 로그
** PHP 에러 로그 혹은 어플리케이션 로그는 어디에 쌓이는가?
- phpinfo(); 를 출력해봐서 error_log 부분을 보면 된다고 한다. 
- 그런데 이 값이 no value로 되어있다??
- 이 값이 no value이면 에러 로그를 부모 에러 로거로 넘긴다고 한다. 
- 부모 에러 로그는 아파치 또는 stderr이다.


** 또한, 로그 레벨은 어디서 변경하는가?



* 각종 지시자들

