#+TITLE: SSL/TLS 暗号設定ガイドライン
#+AUTHOR: IPA

* はじめに
** 書の内容及び位置付け
本ガイドラインは、2018 年 3 月時点における、SSL/TLS 通信での安全性と可用性（相互接続性）
のバランスを踏まえた SSL/TLS サーバの設定方法を示すものである。なお、前バージョン発行以
降の各種動向を踏まえて設定基準の見直しを実施しているため、前バージョン以前の本ガイドラ
インを利用している場合には、今バージョンでの設定要件に基づいた見直しを行い、必要に応じ
て設定変更を実施することを強く推奨する。
本ガイドラインは 9 章で構成されており、章立ては以下のとおりである。
2 章では、本ガイドラインを理解するうえで助けとなる技術的な基礎知識をまとめている。特
に高度な内容は含んでおらず、SSL/TLS 及び暗号についての技術的な基礎知識を有している読者
は本章を飛ばしてもらって構わない。
3 章では、SSL/TLS サーバに要求される設定基準の概要について説明しており、4 章から 6 章
で実現すべき要求設定の考え方を示す。
4 章から 6 章では、3 章で定めた設定基準に基づき、具体的な SSL/TLS サーバの要求設定につ
いて示す。本章の内容は、安全性と可用性を踏まえたうえで設定すべき「要求事項」である。
7 章では、チェックリストの対象には含めていないが、SSL/TLS を安全に使うために考慮すべ
きことをまとめている。本章の内容は、「情報提供」の位置づけとして記載している。
8 章は、クライアントの一つであるブラウザの設定に関する事項を説明しており、ブラウザの
利用者に対して啓発するべき事項を取り上げている。本章の内容は、7 章と同様、「情報提供」の
位置づけのものである。
9 章は、そのほかのトピックとして、SSL/TLS を用いたリモートアクセス技術（“SSL-VPN”と
も言われる）について記載している。本章の内容も「情報提供」の位置づけのものである。
3 章から 6 章が本ガイドラインの最大の特長ともいえ、「暗号技術以外の様々な利用上の判断材
料も加味した合理的な根拠」を重視して現実的な利用方法を目指している。具体的には、実現す
べき安全性と必要となる相互接続性とのトレードオフを考慮する観点から、安全性と可用性を踏
まえたうえで設定すべき「要求設定項目」として 3 つの設定基準（「高セキュリティ型」「推奨セ
キュリティ型」「セキュリティ例外型」）を提示している。
Appendix には、4 章から 6 章までの設定状況を確認するためのチェックリスト等を記載してい
る。チェックリストの目的は、「選択した設定基準に対応した要求設定項目の設定忘れの防止」と
「サーバ構築の作業受託先が適切に要求設定項目を設定したことの確認」を行うための手段とな
るものである。

** 本書が対象とする読者
対象読者は、主に SSL/TLS サーバを実際に構築するにあたって具体的な設定を行うサーバ構築
者、実際のサーバ管理やサービス提供に責任を持つことになるサーバ管理者、並びに SSL/TLS サ
ーバの構築を発注するシステム担当者としている。
一部の内容については、ブラウザを使う一般利用者への注意喚起も対象とする。

* 本ガイドラインの理解を助ける技術的な基礎知識
** SSL/TLS の概要
*** SSL/TLS の歴史
Secure Sockets Layer (SSL)はブラウザベンダであった Netscape 社により開発されたクライアント－サーバモデルにおけるセキュアプロトコルである。SSL には 3 つのバージョンが存在するがバージョン 1.0 は非公開である。SSL2.0 が 1995 年にリリースされたが、その後すぐに脆弱性が発見され、翌 1996 年に SSL3.0 [RFC6101] が公開されている。
標準化団体 Internet Engineering Task Force (IETF)はベンダ間での非互換性の問題を解決するために、Transport Layer Security Protocol Version 1.0 (TLS1.0) [RFC2246] を策定した。TLS1.0 は SSL3.0をベースにしている。TLS1.0 で定められているプロトコルバージョンからも分かるように TLS1.0は SSL3.1 とも呼ばれる。
TLS1.1 [RFC4346] は、TLS1.0 における暗号利用モードの一つである CBC[ 1]モードで利用される初期ベクトルの選択とパディングエラー処理に関連する脆弱性に対処するために仕様策定が行われた。具体的には BEAST[ 2]攻撃を回避することができる。
さらに TLS1.2 [RFC5246] は特にハッシュ関数 SHA-2 family (SHA-256 や SHA-384)の利用など、より強い暗号アルゴリズムの利用が可能になった。例えばメッセージ認証コード（MAC[ 3]）や擬似乱数関数にて SHA-2 family が利用可能になっている。また認証暗号が利用可能な暗号スイートのサポートがなされており、具体的には GCM[ 4]や CCM[ 5]モードの利用が可能になった。
表 3 に SSL/TLS のバージョンの概要をまとめる。最近では、IETF において、TLS1.3 の規格化の議論が進んでいる。
なお、SSL/TLS に対する攻撃方法の技術的な詳細については、「CRYPTREC 暗号技術ガイドライン（SSL/TLS における近年の攻撃への対応状況）[ 6]」を参照されたい。

*** プロトコル概要
SSL/TLSはセッション層に位置するセキュアプロトコルで、通信の暗号化、データ完全性の確保、サーバ（場合によりクライアント）の認証を行うことができる。セッション層に位置することで、アプリケーション層ごとにセキュリティ確保のための仕組みを実装する必要がなく、HTTP、SMTP、POPなど様々なプロトコルの下位に位置して、上記の機能を提供することができる。

SSL/TLSでは、暗号通信を始めるに先立って、ハンドシェイクが実行される（図 1参照）。
ハンドシェイクでは、①ブラウザ（クライアント）とサーバが暗号通信するために利用する暗号アルゴリズムとプロトコルバージョンを決定し、②サーバ証明書によってサーバの認証を行い、③そのセッションで利用するセッション鍵を共有する、までの一連の動作を行う。
その際、SSL/TLSでは相互接続性の確保を優先してきたため、一般には複数の暗号アルゴリズムとプロトコルバージョンが実装されている。結果として、暗号通信における安全性強度は、ハンドシェイクの①の処理でどの暗号アルゴリズムとプロトコルバージョンを選択したかに大きく依存する。
サイトの身分証明ともいえるサーバ証明書は、Trusted Third Partyである認証局（CA[9]）によって発行されるのが一般的であり、特にWeb Trust for CAなどの一定の基準を満たしている代表的な認証局の証明書はルートCAとして予めブラウザに登録されている。(4)の検証では、ブラウザに登録された認証局の証明書を信頼の起点として、当該サーバ証明書の正当性を確認する。

*** TLS1.3の概要
TLS1.3は、TLS1.2策定以降に見つかった新たな脆弱性や攻撃手法への対策を施すと共に、QUIC等のプロトコルに対応するための性能向上を狙いとして、プロトコルと暗号アルゴリズムの抜本的な再設計が行われた。最新仕様はdraft28であり、2018年3月にRFC Editor Queueに進み、RFC発効前の最終作業が続いている（2018年4月現在）。
TLS1.2（以前）との差異の観点から見た主な特徴を以下に示す。
- 脆弱なアルゴリズムとして、Triple DES、DSA、RC4、MD5、SHA-1、SHA-224、静的なRSAが削除された。また、認証暗号（AEAD）でないAESのCBCモードが削除された。
- NIST FIPS/SPで規定されていないアルゴリズムとして、共通鍵暗号のChaCha20と署名のEdDSAが追加された。
- 鍵交換は、DHE、ECDHE、PSKのみが規定され、ECDHEが必須になった。
- 楕円曲線としてsecp256r1が必須になった。
- ハッシュ関数はSHA-256が必須になった。
- 脆弱なハンドシェイク機能として、 *リネゴシエーション、圧縮、セッション回復* が削除された。
- HMACベースの導出関数（HKDF-Expand(・), HKDF-Extract(・)）を使った鍵導出に変更された。
- ServerHello以降のハンドシェイクパラメータを暗号化して保護する
- 性能向上のため、1-RTTでハンドシェイクが完了するようにメッセージおよび拡張が見直された。
- QUIC等への適用を考慮し、0-RTTでアプリデータを送信する機能が追加された。
- ClientHello、ServerHello、ChangeCipherSpecのTLS1.2互換性を保つことにより、中間ノードによる接続性を向上した。

*** TLSプロトコルの最新動向
TLS1.3がまもなくRFCとして発行されるのを受け（ガイドライン発行時の状況によっては文章修正の可能性有り）、2017年11月にNISTはTLSに関する新たなガイドラインのドラフト版[10]を発表した。このドラフト版では、2020年1月1日までに、①連邦政府で利用する全てのサーバ及びクライアント（ブラウザ）でTLS1.2をサポートすることを要求するとともに、②TLS1.3をサポートし移行する計画を作るよう勧告する、内容になっている。
また、2015年4月以降に発行されたSSL/TLSに関するRFC 32件のうち、「プロトコルバージョン」「サーバ証明書」「暗号スイート（暗号アルゴリズム）」の3つの観点から、利用可否や利用期間などの記述が含まれるものは、以下のとおりである。例えば、既存のTLS1.2までのプロトコルに対して、SSL3.0の無効化やRC4の無効化など、プロトコルの脆弱性の排除に関するものが規格化されている。


** 暗号アルゴリズムの安全性
*** CRYPTREC暗号リスト
総務省と経済産業省は、暗号技術に関する有識者で構成されるCRYPTREC活動を通して、電子政府で利用される暗号技術の評価を行っており、2013年3月に「電子政府における調達のために参照すべき暗号のリスト(CRYPTREC暗号リスト)」を策定した[11]。CRYPTREC暗号リストは、「電子政府推奨暗号リスト」、「推奨候補暗号リスト」及び「運用監視暗号リスト」で構成される。
「政府機関の情報セキュリティ対策のための統一基準（平成28年度版）」（平成28年8月31日、サイバーセキュリティ戦略本部）では以下のように記載されており、政府機関における情報システムの調達及び利用において、CRYPTREC暗号リストのうち「電子政府推奨暗号リスト」が原則的に利用される。

*** 異なる暗号アルゴリズムにおける安全性の見方
異なる技術分類の暗号アルゴリズムを組合せて利用する際、ある技術分類の暗号アルゴリズムの安全性が極めて高いものであっても、別の技術分類の暗号アルゴリズムの安全性が低ければ、結果として、低い安全性の暗号アルゴリズムに引きずられる形で全体の安全性が決まる。逆に言えば、異なる技術分類の暗号アルゴリズムであっても、同程度の安全性とみなされている暗号アルゴリズムを組合せれば、全体としても同程度の安全性が実現できることになる。

異なる技術分類の暗号アルゴリズムについて同程度の安全性を持つかどうかを判断する目安として、“ビット安全性（等価安全性ということもある）”という指標がある。具体的には、評価対象とする暗号アルゴリズムに対してもっとも効率的な攻撃手法を用いたときに、どの程度の計算量があれば解読できるか（解読計算量[12]）で表現され、鍵長[13]とは別に求められる。表記上、解読計算量が2xである場合に“xビット安全性”という。例えば、共通鍵暗号においては、全数探索する際の鍵空間の大きさで2x（xは共通鍵のビット長）、ハッシュ関数の例としては、一方向性で2x、衝突困難性で2^(x/2)（xは出力ビット長）が解読計算量の（最大）理論値である。



* 設定基準の概要 
本章では、SSL/TLSサーバの構築時に、主に暗号通信に関わる設定に関しての要求事項を決めるために考慮すべきポイントについて取りまとめる。

** 実現すべき設定基準の考え方
SSL/TLSは、1994年にSSL2.0が実装されて以来、その利便性から多くの製品に実装され、利用されている。一方、プロトコルの脆弱性に対応するため、何度かプロトコルとしてのバージョンアップが行われている影響で、製品の違いによってサポートしているプロトコルバージョンや暗号スイート等が異なり、相互接続性上の問題が生じる可能性がある。
本ガイドラインでは、安全性の確保と相互接続の必要性のトレードオフにより、「高セキュリティ型」「推奨セキュリティ型」「セキュリティ例外型」の3段階の設定基準に分けて各々の要求設定を定める。それぞれの設定基準における、安全性と相互接続性についての関係は表6のとおりである。

実際にどの設定基準を採用するかは、安全性の確保と相互接続の必要性の両面を鑑みて、サーバ管理やサービス提供に責任を持つ管理者が最終的に決定すべきことではあるが、本ガイドラインでは、安全性もしくは相互接続性についての特段の要求がなければ「推奨セキュリティ型」の採用を強く勧める。本ガイドラインの発行時点では、「推奨セキュリティ型」がもっとも安全性と可用性（相互接続性）のバランスが取れている要求設定であると考えている。

안전성과 상호접속성은 트레이드-오프 관계
어느쪽을 중시할 것인가에 따라 '고 시큐리티 형', '추천 시큐리티 형', '시큐리티 예외형' 중에서 하나를 선택해서 적용하라. 다만 특별한 의견이 없을 때는 '추천 시큐리티 형'을 적용하라. 가장 밸런스가 좋다. 

「セキュリティ例外型」は、システム等の制約上、脆弱なプロトコルバージョンであるSSL3.0の利用を全面禁止することが現実的ではなく、安全性上のリスクを受容してでもSSL3.0を継続利用せざるを得ないと判断される場合にのみ採用すべきである。なお、セキュリティ例外型であっても、SSL3.0の無期限の継続利用を認めているわけではなく、近いうちにSSL3.0を利用不可に設定するように変更される可能性がある。

また、SSL3.0を利用する関係から、利用可能な暗号スイートの設定においても、脆弱な暗号アルゴリズムであるRC4の利用を認めている。ただし、本来的にはRC4はSSL3.0に限定して利用すべきであるが、TLS1.0以上のプロトコルバージョンでRC4の利用を不可にする設定を行うことが難しいため、TLS1.0以上であってもRC4が使われる可能性が排除できないことにも注意されたい。

또한 SSL3.0을 이용하는 관계로 사용 가능한 암호화 도구 모음 설정에서도 취약한 암호화 알고리즘 인 RC4의 사용을 인정하고있다. 그러나 본래는 RC4는 SSL3.0에 한정하여 이용해야하지만, TLS1.0 이상의 프로토콜 버전 RC4의 이용을 불가능하게하는 설정을 하기 어렵기 때문에 TLS1.0 이상이어도 RC4가 사용될 가능성을 배제 할 수없는 것에 주의하기 바란다.

したがって、セキュリティ例外型を採用する際は、推奨セキュリティ型への移行完了までの短期の暫定運用として、移行計画や利用終了期限を定めたりするなど、今後への具体的な対処方針の策定をすべきである。


** 要求設定の概要
SSL/TLSにおける暗号通信に関わる設定には以下のものがある。
- プロトコルバージョンの設定
- サーバ証明書の設定
- 暗号スイートの設定
- SSL/TLSを安全に使うために考慮すべきこと

** チェックリスト
図 7に高セキュリティ型のチェックリストのイメージを示す。
チェックリストの目的は、

- 選択した設定基準に対応した要求設定項目をもれなく実施したことを確認し、設定忘れを防止すること
- サーバ構築の作業受託先が適切に要求設定項目を設定したことを、発注者が文書として確認する手段を与えること

である。したがって、選択した設定基準に応じたチェックリストを用い、すべてのチェック項目について、該当章に記載の要求設定に合致していることを確認して「済」にチェックが入ることが求められる。


* プロトコルバージョンの設定
SSL/TLSは、1994年にSSL2.0が実装され始めた後、2014年3月現在の最新版となるTLS1.2まで5つのプロトコルバージョンが実装されている。4.1節にプロトコルバージョンについての要求設定をまとめる。4.2節にプロトコルバージョンごとの安全性の違いを記す。

** プロトコルバージョンについての要求設定
基本的に、プロトコルのバージョンが後になるほど、以前の攻撃に対する対策が盛り込まれるため、より安全性が高くなる。しかし、相互接続性も確保する観点から、多くの場合、複数のプロトコルバージョンが利用できるように実装されているので、プロトコルバージョンの選択順位を正しく設定しておかなければ、予想外のプロトコルバージョンでSSL/TLS通信を始めることになりかねない。

そこで、SSL2.0からTLS1.2までの安全性の違い（4.2節表 8参照）を踏まえ、SSL/TLSサーバがサポートするプロトコルバージョンについての要求設定を以下のように定める。なお、高セキュリティ型の要求設定ではサーバとクライアントの両方がTLS1.2をサポートしていることが必須となることに注意されたい。

*** 高セキュリティ型の要求設定
- TLS1.2を設定有効にする
- TLS1.1以前を設定無効（利用不可）にする

*** 推奨セキュリティ型の要求設定
- SSL3.0及びSSL2.0を設定無効（利用不可）にする
- TLS1.1、TLS1.2については、実装されているのであれば、設定有効にする
- プロトコルバージョンの優先順位が設定できる場合には、設定有効になっているプロトコルバージョンのうち、最も新しいバージョンによる接続を最優先とし、接続できない場合に順番に一つずつ前のプロトコルバージョンでの接続するように設定することが望ましい

*** セキュリティ例外型の要求設定
- SSL2.0を設定無効（利用不可）にする
- TLS1.1、TLS1.2については、実装されているのであれば、設定有効にする
- プロトコルバージョンの優先順位が設定できる場合には、設定有効になっているプロトコルバージョンのうち、最も新しいバージョンによる接続を最優先とし、接続できない場合に順番に一つずつ前のプロトコルバージョンでの接続するように設定することが望ましい



* サーバ証明書の設定


* 暗号スイートの設定


* SSL/TLSを安全に使うために考慮すべきこと

* ブラウザを利用する際に注意すべきポイント

* その他のトピック



[fn:1] https://www.ipa.go.jp/security/ipg/documents/ipa-cryptrec-gl-3001-2.0.pdf
