#+TITLE: 정보보안에 관한 법령

* 컴퓨터 범죄를 관리하는 법률
** 컴퓨터 범죄를 관리하는 법률(형법)의 개요
- 일본은 오랫동안 컴퓨터 범죄나 네트워크 범죄를 벌하는 법률이 없는 것이 문제였다. 
- 이전의 형법으로는 물리적인 현실세계에서 사람 대 사람이 직접하는 행위가 전제되어 있었다. 
- 때문에 사람이 컴퓨터나 네트워크 시스템, 데이터 등에 대해서 행하는 범죄는 벌하기가 어려웠다.
- 이 것이 1987년에 개정되었으며 대표적인 것을 소개한다. 

*** 전자계산기 손해 등 업무방해 (형법제234조2)
다음과 같은 행위로 컴퓨터나 시스템에 본래의 목적과 다른 동작을 하게해 업무를 방해한 경우에는 벌한다. 
- 컴퓨터 자체 또는 컴퓨터에서 사용하는 전자 데이터를 파괴한다.
- 컴퓨터에 거짓정보나 부정한 명령을 전달한다. 
- 컴퓨터의 동작환경면에서 방해를 한다. 

*** 전자계산기 사용사기 (형법제246조2)
다음과 같은 행위로 재산상의 불법 이익을 얻거나 타인에게 얻도록 하는 경우는 벌한다. 
- 컴퓨터나 시스템에 거짓 정보나 부정명령을 전달하여 재산권에 관한 부실 전자 데이터를 만든다. 
- 재산권에 관한 거짓 전자 데이터를 사용한다. 


** 부정 액세스 행위 금지에 관한 법률 (부정 액세스 방지법)의 개요
1987년 컴퓨터 범죄를 관리하는 법률의 개정으로 컴퓨터나 전자 데이터에 대한 행위를 벌할 수 있게 되었지만 인터넷을 중심으로 한 컴퓨터 이용환경에 대해서는 벌할 수 없는 경우가 다수 발생했다. 예를 들면 다음과 같은 경우다. 

- 액세스 권한이 없는 타인의 사이트에 마음대로 액세스한다. 
- 그에 더해 그 사이트에 있는 정보를 들여다보거나 패스워드 등의 정보를 훔치거나 공개한다. 
- 그에 더해 그 시스템 자원을 사용해 어떤 처리를 실행하거나 서비스를 이용한다. 
- 타인의 사이트의 약점을 마음대로 조사하여 공개한다. 

이러한 행위에 의해 결과적으로 *형법에 정해진 피해가 발생하면* 처벌의 대상이 되지만 그렇지 않은경우는 *행위 그 자체를 벌하는 것은 할 수 없었다.* 여기에서 *구체적인 피해가 발행하지 않아도 권한을 가지지 않은 자가 다른 자의 사이트의 네트워크를 이용해서 마음대로 액세스하는 행위* 나 *그 것을 조장하는 행위* 등을 벌하기 위해서 2000년 2월 13일에 *부정액세스 방지 등에 관한 법률*, 이른바 '*부정액세스금지법*' 이 시행되어 2012년 5월에 개정되었다. 부정 액세스 금지법의 특징은 다음과 같다. 

- 구체적인 피해가 발생하지 않아도 부정액세스를 한 사실만으로 벌할 수 있다. 
- 부정 액세스의 대상이 되는 컴퓨터에 적절한 부정 액세스 대책이 되어 있는 것이 전제이다. 
- 네트워크를 통한 리모트에서 이루어지는 행위가 전제이다. 
- 타인의 패스워드를 마음대로 공개하거나 판매하는 행위도 처벌의 대상이 된다. 
- 피싱 사기등 부정 액세스를 목적으로 타인의 ID나 패스워드를 취득하는 행뒤도 처벌의 대상이 된다. 

이처럼 피해의 유무에 관계없이 *부정하다고 인식되는 행위를 한 시점* 에서 처벌의 대상이 되는 것이 큰 특징이다. 


** 컴퓨터 바이러스의 작성이나 보관을 벌하는 법개정
이전에는 컴퓨터 바이러스를 작성하거나 배포하는 행위를 벌하는 법령이 없어서 그 것으로 타인의 업무를 방해하는 등의 사실이 인정되지 않으면 벌하기 어려웠다. 이 법을 고쳐서 컴퓨터 바이러스를 작성 보관하는 행위 등(바이러스 작성죄)를 벌하는 형법개정안인 '정보처리의 고도화 등에 대처하기 위한 형법등의 일부 개정하는 법령안'이 2011년 6월 작성되었다. 

이 법개정으로 바이러스 작성, 제공 등을 한 경우 3년이하의 징역 또는 50만엔 이하의 벌금이 부과되게 되었다. 또한 다른 컴퓨터를 감염, 발병시킬 목적으로 의도적으로 바이러스를 취득 보관한 경우 2년이하의 징역 또는 30만엔 이하의 벌금이 부여된다. 

한번 이 법을 악용해 타인에게 바이러스를 보내서, 의도하지 않게 보유하게 되는 경우나 바이러스 대책에 관한 조사, 연구 등을 목적으로 하는 경우는 어떻게 되는 것인가 등의 의문의 목소리도 높아지고 있다. 이에 대해 법무성에서는 다음을 만족하지 않으면 죄가 되지 않는다고 하고 있다. 

- 정당한 이유없이 바이러스 작성/보유
- 무단으로 타인의 컴퓨터에 실행시키는 것을 목적으로 하고 있다


* 사이버 보안 기본법


* 전자서명법


* 통신도청법


* 특정전자메일법





