* 개념
- TCP 통신의 정당성을 확인하기 위해 SYN/ACK 패킷의 시퀀스 번호안에 들어가 있는 데이터이다.
- SYN flood 공격을 막기 위해 사용된다. 
- Daniel J. Bernstein 가 발명

* 동작
클라이언트로부터 SYN 패킷을 받은 단계에서는 아직 TCP 소켓을 열지않고, SYN/ACK 패킷안에 SYN 쿠키를 삽입하여 클라이언트에게 회신한다.
그리고 클라이언트로부터 ACK 패킷이 오면, 정당성을 확인(SYN 쿠키 값 확인)한 후에 TCP 소켓을 열고 연결을 확립한다. 

** 하지만 이 동작이 어떻게 SYN Flooding에 대한 방어가 되는가?
SYN Flooding은 서버측의 메모리를 고갈시키는 공격인데, SYN 쿠키를 사용했을 경우에는 



* 효과
SYN queue가 꽉 찼을 때 더 이상 연결이 안되는 현상을 막아준다? 라고 하는데



* 적용되어 있는지 확인방법
/etc/sysctl.conf 파일에서 다음을 확인

net.ipv4.tcp_syncookies 의 값이 1로 설정되어 있으면 SYN 쿠키 방식이 동작중이다. 

(우분투를 테스트해봤는데 동작하지 않는 것이 기본설정인 듯하다. )


* 단점
TCP 옵션을 사용할 수가 없어서 성능에 악영향을 미칠 수 있다고 한다. 

* 궁금점
** SYN쿠키를 사용할 때도 미연결 백로그 큐가 쌓이는가?
백로그 큐는 접속 요청 패킷(SYN)을 받은 후, 클라이언트로부터 (ACK)을 아직 받지 못했을 때 연결상태를 저장하는 메모리 공간이라고 한다. SYN 쿠키 방식으로 동작중인 서버에서도 백로그 큐를 사용하는가?

=> 사용하는 것 같다. 정확히는, 평소에는 SYN쿠키를 사용하고 있지 않다가 SYN Flooding 공격이 의심될 때만 사용하도록 모드가 변경되는 것 같다. 즉, 평소에는 SYN요청이 백로그 큐에 쌓이다가 꽉 차면 (SYN Flooiding 공격이 의심되면) SYN쿠키를 발행하는 방식으로 바뀌는 것 같다. 정리하면 평소 모드에서는 백로그 큐(SYN queue)를 사용하다가 SYN쿠키 방식으로 바뀌면 사용하지 않는 것 같다. 왜 이렇게 생각하냐면, 
possible SYN flooding on port 80. Sending cookies. 라는 메세지 로그의 개수가 그렇게 많이 쌓이지 않는다. 많아봐야 1분당 몇십개 수준. 

http://cosk.net/bbs/content.php?board=hkbbs_tip&bbs_no=3924 에도 동일한 내용이 있는 것으로 봐서 맞다고 생각한다. 



** 백로그 큐의 크기를 증가시키는 방법은?
/etc/sysctl.conf에서 net.ipv4.tcp_max_syn_backlog 값을 변경한다.


* 참고 URL
https://en.wikipedia.org/wiki/SYN_cookies


