* 1.2 정보보안의 특징과 기본적인 사고방식

** 1.2.1 정보보안의 세가지 특성

*** 기밀성 (Confidentiality)
권한을 가진자만이 범위내에서 허가된 활동(읽기,쓰기,실행,보기 등)을 할 수있게 하는 것. 

접근 제어, 인증, 암호화 등의 기술을 사용해서 확보한다.

*** 완전성 (Integrity)
데이터의 정당성, 정확성, 망라성, 일관성 등을 유지하는 특성. 

해시나 디지털 서명등을 이용.

*** 가용성 (Availability)
정보 시스템이 필요한 때에 언제든지 서비스가 제공될 수 있는 상태를 유지하는 특성. 

시스템이나 네트워크 설비의 이중화, 시스템 리소스(CPU, 메모리, 디스크 등) 등의 충분한 확보,데이터 백업, 정기유지보수 등으로 확보.


** 1.2.2 정보보안의 부가적인 특성
*** 진정성 (Authenticity)
이용자, 프로세스, 시스템 정보 등이 주장대로인 것을 확실히하는 특성. 

강화 인증같은 개념인가. 

정보에서는 메세지 인증등을 사용, 본인 인증에서는 복수의 인증 요소 (패스워드, IC카드, 생체정보, 디지털 증명서등)을 사용.


*** 책임추적성 (Accountability)
이용자, 프로세스, 시스템 등의 동작에 있어서 동작내용을 모두 추적가능할 것을 확실히하는 특성. 

기록, 로그 등.

*** 부인방지 (Non-repudiation)
증적(책임 추적성에서의 로그 등)의 완전성을 확보하는 것으로 가능함. 

디지털 서명등을 활용. 

*** 신뢰성 (Reliability)
정보 시스템에서 처리의 결과에 모순이 없고, 기대되는 대로 동작하는 것을 확실히 하는 특성. 

시스템 유지보수, 점검, 테스트 강화 등. 


** 1.2.3 정보보안대책의 기능
*** 억지, 억제
인간의 의식이나 모럴에 대해 범죄나 부정행위를 생각하지 못하도록하여, 문제의 발생을 미연에 방지하는 것. 

주된 대상은 사원이나 파견사원 등 내부의 요인이다. 

정보보안 정책의 운용, 교육, 실시, 준수상태 감사, 내부 네트워크 감시 등. 

실제로 네트워크를 감시하고 있지 않아도 감시하고 있다고 공지하는 것 만으로도 억제효과가 있다. 

*** 예방, 방지
조직, 물리환경, 정보시스템 등 취약한 부분에 대해 미리 충분한 정보보안 대책을 준비해놓는 것. 

기기나 설비 정기보수, 취약점 검사, 소프트웨어 버전 업그레이드, 유저 인증, 접근 제어, 기밀 데이터의 암호화 등. 

*** 검치, 추적
사이버 공격이나 내부 범죄의 발생을 빠르게 발견, 통지하는 것과 동시에 그 원인과 영향범위 등의 특정에 필요한 정보를 확보하는 것으로 문제의 확산을 막고, 손실을 최소한으로 억누르는 기능이다. 

멀웨어 상시 감사, 로그 수집/분석, 컴퓨터/네트워크 가동 상황 감시, 침입탐지 시스템에 의한 실시간 접근 감시, 사무실 출입 기록 및 감시 카메라 등.  

*** 복구 
사이버 공격이나 내부 범죄, 기기 장애 등으로 문제가 발생했을 때 빠르게 정보 시스템이나 네트워크를 정상상태로 복구하는 기능. 

백업 데이터의 출력과 보존, 복구순서 매뉴얼, 로그의 출력 및 보존 등의 명확화, 불시사태 발생을 상정한 훈련등을 실시하는 것 등.  

** 1.2.4 정보보안 대책의 기본적인 사고방식
*** 대책을 검토하기 전에 리스크 분석, 평가를 실시한다. 
이로서 실시할 대책의 목적이나 효과를 명확히 할 수 있다.

*** 지켜야할 것(정보 자산, 시스템 등)을 인식한다.

*** 위협을 이해한다.
내부의 위협에 대해서는 대책을 통해 경감시키는 것이 능가능하지만 자연재해나 조직외부의 공격에 대해서는 불가

*** 취약점을 이해하고 대처한다.
조직이나 정보시스템 등에 내재하고 있는 다양한 약점이나 결함을 파악하고 대처하는 것. 

*** 정보보안의 방침, 기준을 명확히 하고, 순서 등을 정비한다.
이로서 한정된 예산, 요인, 설비등의 리소를 유효하게 활용한다.

그리고 대책을 명확하게 실시하고 실수 발생을 막기위해 순서 매뉴얼등을 정비한다.

*** 보안과 편의성의 밸런스를 잡는다.
일반적으로 보안과 편의성은 트레이드오프 관계. 

리스크를 충분히 고려한 상태에서 편의성과의 밸런스를 잡는다. 

*** 사고를 미연에 방지하기 위한 노력을 하면서 발생시에는 준비한 대처를 확실히 실시한다.

*** 실시한 대처의 유효성에 대해 제 삼자에 의한 리뷰를 실시한다.
대책에서 빠진 점 등을 발견하고, 제정, 개선등을 하기 위해 제 삼자에 의한 리뷰를 실시한다. 

리뷰는 조직이나 정보 시스템에 변화가 있을 때, 그리고 최저 1년에 1회정도로 정기적으로 실시한다. 

*** 최소권한의 원칙을 철저히 한다.
정보자산에 접근하는 인간, 프로세스, 프로그램 등에 대해 항상 필요 최소한의 권한만을 부여하도록 하는 것. 

따라서, 특권 계정이나 관리자 계정 등의 취급관리에는 주의가 필요.

또한, 계정의 유효기간도 최소한도로 할 필요가 있다.

*** 책무의 분리 원칙을 철저히 한다.
동일 인물이 복수의 업무를 담당할 때, 각자 별도의 권한을 부여해야 한다는 것. 

단순히 분리하는 것 만이 아니라 제3자에 의한 감시, 감사를 하는 것으로 견제효과를 볼 수 있다.

*** 중요정보를 취급하는 시스템과 인터넷 접속환경을 분리한다.
물리적으로 분리하기 어려운 경우에는 VDI등을 이용해서 논리적으로 분리하는 것도 유효하다.

*** Fail Safe 를 고려한 시스템을 설계, 구축한다.
페일 세이프란 시스템에 장애가 생겼을 경우 안전한 방향으로 가도록 설계, 구축하는 것으로 피해를 최한으로 하는 방법이다.

예를들면, 파이어월에 장애가 생겼을 경우 모든 패킷이 통과하지 못하도록 하는 것 등. 

현실적으로는 장애발생 시에 업무나 서비스의 계속성을 우선하기 때문에 보안을 희생하는 경우도 있지만 기본적인 사고방식으로 인식해둘 필요가 있다.

*** 시스템의 구성과 기능을 단순히 한다. 
네트워크 구성이나 서버의 구성 및 기능이 단순할수록 보안을 확보하기도 쉬워진다.

예를들어, 한 서버가 여러가지 역할을 할 경우, 장애 발생 시 원인규명이 어려워 지거나, 특정 소프트웨어가 다른 소프트웨어에 영향을 주는 등의 문제가 발생할 가능성이 있다. 

또한, 시스템에서 불필요한 기능을 모두 무효로 해두는 것도 리스크 경감에서 중요하다.
  
*** 시스템이나 설비의 중요한 기능을 분산화한다.
시스템 장애 시의 대처를 위함.

또한, 모바일 PC와 그 인증장치를 분리해서 관리하는 것도 도난시의 리스크를 경감시키는 분산화 대책의 하나의 예이다.

*** 이중, 삼중의 대책을 실시한다.(다층방어)
OS, 미들웨어, 어플리케이션의 취약점을 대응하고, IPS,IDS,WAF등의 설치운용도 함께 하는 등. 

그리고 결제 시스템같은 곳에서는 단말의 인증 -> 본인 인증 -> 마지막으로 결제 직전에 추가 본인 인증 등을 실시. 


*** 이용자를 식별, 추적 및 검증을 가능하도록 한다.
이를 위해서 각 이용자마다 하나의 계정을 부여하는 것, 활동 로그를 보존하고 로그의 수정, 소실등이 발생하지 않도록 대책을 마련할 필요가 있다.


